### ISSUE TITLE
[BUG] cannot open any note with this plugin enabled

### ISSUE THREAD

**Issue by deafmute1** [Quorafind/Outliner.MD#82]
Console Error:
```
RangeError: Field is not present in this state
    at e.field (app.js:1:285075)
    at new Yo (plugin:outliner-md:80:740)
    at e.update [as updateF] (plugin:outliner-md:80:2122)
    at Object.update (app.js:1:275079)
    at e.computeSlot (app.js:1:285929)
    at Ve (app.js:1:279023)
    at new e (app.js:1:284898)
    at e.applyTransaction (app.js:1:285884)
    at e.get (app.js:1:281027)
    at e.update (app.js:1:442651)
```
Obsidian Version: 1.6.7 (Installer 1.6.7) 
OS: MacOS 14.5
Outerline.md: 0.1.8 via BRAT.

**Comment by Quorafind** [comment]
Should be fixed in latest version. Please tell me if this issue remains.
